name: Postman Collection Runner

on:
  push:
    branches:
      - main

jobs:
  run_postman_collection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Newman
        run: npm install -g newman && npm install -g newman-reporter-html

      - name: Run Postman Collection
        run: |
          newman run query-runner.json \
            --iteration-data inputs.csv \
            --reporters cli,html \
            --reporter-html-export /tmp/postman/report.html \
            --delay-request 1000 --bail

      - name: Upload HTML Report
        uses: actions/upload-artifact@v2
        with:
          name: postman-html-report
          path: /tmp/postman/report.html
